/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.awt.AWTException;
import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException, AWTException {
        // TestCases tests = new TestCases(); // Initialize your test class
        // TODO: call your test case functions one after other here
        // tests.testCase01();
        // END Tests
        // tests.endTest(); // End your test by clearning connections and closing
        // browser
        // Search_Amazon s = new Search_Amazon();
        // s.Find();
        // s.endTest();
        // BookMySHow b = new BookMySHow();
        // b.findlinks();
        // b.endTest();
        // Automate_post_on_linkedin l = new Automate_post_on_linkedin();
        // l.linkedinPost();
        // Automate_imdb_ratings a = new Automate_imdb_ratings();
        // a.imdb_rating();
        // a.endTest();

        // Automate_image_urls a = new Automate_image_urls();
        // a.automate_image_urls();
        // a.endTest();

        // Automate_nested_frames_text a = new Automate_nested_frames_text();
        // a.nested_frames();
        // a.endTest();

        // Automate_window_handle a = new Automate_window_handle();
        // a.window_handle();
        // a.endTest();

        Uploadfile u = new Uploadfile() ;

        u.fileupload();

    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException, AWTException {
        new App().getGreeting();
    }
}
